/**
 * PROJECT AS ABOVE, SO BELOW
 * Module: OTU Importer
 * Description: Handles the "Import the Imperium" feature.
 *   - Loads the sector list from /sectors/imperium.tsv
 *   - Presents a modal for sector selection and slot assignment
 *   - Fetches each selected sector from the travellermap API
 *   - Feeds the result into the existing importT5Tab parser
 *
 * Sean Protocol: Zero RPG logic here. Pure orchestration and UI.
 */

(function () {
    'use strict';

    /**
     * Sector list is provided by js/imperium_data.js (auto-generated by convert_imperium.ps1).
     * Re-run convert_imperium.ps1 whenever sectors/imperium.tsv changes.
     */
    function getImperiumSectors() {
        if (!window.IMPERIUM_SECTORS || window.IMPERIUM_SECTORS.length === 0) {
            throw new Error('Sector list not loaded. Run convert_imperium.ps1 to generate js/imperium_data.js.');
        }
        return window.IMPERIUM_SECTORS;
    }

    const CACHE_PREFIX = 'otu_cache_';
    const CACHE_TTL_MS = 24 * 60 * 60 * 1000; // 24 hours

    /**
     * Returns cached TSV text for a sector if it exists and is less than 24 hours old.
     * Returns null on a miss, an expired entry, or any storage error.
     */
    function getCachedSector(name) {
        try {
            const raw = localStorage.getItem(CACHE_PREFIX + name);
            if (!raw) return null;
            const entry = JSON.parse(raw);
            if (!entry || !entry.timestamp || !entry.data) return null;
            if (Date.now() - entry.timestamp > CACHE_TTL_MS) return null;
            return entry.data;
        } catch (e) {
            return null;
        }
    }

    /**
     * Fetches a sector from the travellermap API, writes it to localStorage,
     * and returns the raw TSV text. Silently skips the cache write if storage
     * is full (QuotaExceededError) so the import still completes.
     */
    async function fetchAndCacheSector(name) {
        const url = `https://travellermap.com/data/${encodeURIComponent(name)}/tab`;
        const response = await fetch(url);
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
        const text = await response.text();
        try {
            localStorage.setItem(CACHE_PREFIX + name, JSON.stringify({
                timestamp: Date.now(),
                data: text
            }));
        } catch (e) {
            // QuotaExceededError or similar — cache write skipped, import continues.
            console.warn(`[OTU Importer] Could not cache "${name}": ${e.message}`);
        }
        return text;
    }

    /**
     * Returns true if a sector slot already contains non-empty hex data.
     * Used for the pre-flight collision check.
     */
    function sectorSlotHasData(slot) {
        // Convert slot label to numeric sector ID so the prefix matches
        // the numeric hexId format used since the v0.7.3 refactor.
        const num = sectorSlotToNumber(slot);
        const prefix = num + '-';
        for (const [hexId, state] of hexStates) {
            if (hexId.startsWith(prefix) && state && state.type !== 'EMPTY') {
                return true;
            }
        }
        return false;
    }

    /**
     * Open the Import the Imperium modal.
     */
    function openImperiumModal() {
        try {
            renderModal(getImperiumSectors());
        } catch (err) {
            alert(`Failed to load sector list: ${err.message}`);
        }
    }

    /** Build and display the modal sector list. */
    function renderModal(sectors) {
        const list = document.getElementById('otu-sector-list');
        list.innerHTML = '';

        sectors.forEach((sector, idx) => {
            const row = document.createElement('label');
            row.className = 'otu-sector-row';
            row.style.cssText = [
                'display:flex', 'align-items:center', 'gap:8px',
                'padding:6px 10px', 'border-radius:4px',
                'border-left:3px solid transparent',
                'cursor:pointer', 'transition:background 0.15s, border-color 0.15s',
                'background:#0d1117'
            ].join(';');

            row.innerHTML = `
                <input type="checkbox" class="otu-sector-check" data-idx="${idx}" checked
                    style="flex-shrink:0; cursor:pointer; accent-color:#66fcf1;">
                <span class="otu-sector-name"
                    style="color:#c5c6c7; font-size:0.85rem; white-space:nowrap;">${sector.name}</span>
                <span style="flex:1; border-bottom:1px dotted #2a3a3a; margin:0 4px; height:1px; align-self:center;"></span>
                <input type="text" class="otu-sector-slot" value="${sector.defaultSlot}"
                    maxlength="2" size="2"
                    style="width:32px; padding:2px 4px; background:#1f2833; border:1px solid #45a29e;
                           color:#66fcf1; font-family:'Courier New',monospace; font-size:0.85rem;
                           text-align:center; text-transform:uppercase; border-radius:3px;"
                    onclick="event.stopPropagation();">
            `;

            // Highlight row on hover
            row.addEventListener('mouseenter', () => {
                row.style.background = '#1a2535';
                row.style.borderLeftColor = '#45a29e';
            });
            row.addEventListener('mouseleave', () => {
                row.style.background = '#0d1117';
                row.style.borderLeftColor = 'transparent';
            });

            list.appendChild(row);
        });

        // Reset select-all to checked
        const selectAll = document.getElementById('otu-select-all');
        if (selectAll) selectAll.checked = true;

        document.getElementById('otu-import-modal').style.display = 'flex';
    }

    /** Close the modal. */
    function closeModal() {
        document.getElementById('otu-import-modal').style.display = 'none';
    }

    /**
     * Pre-flight check, then fetch and import each selected sector in sequence.
     */
    async function runImport() {
        const rows = document.querySelectorAll('.otu-sector-row');
        const selected = [];

        const sectors = getImperiumSectors();
        rows.forEach((row, idx) => {
            const cb = row.querySelector('.otu-sector-check');
            const slotInput = row.querySelector('.otu-sector-slot');
            const slot = (slotInput ? slotInput.value.trim() : '').toUpperCase();
            if (cb && cb.checked && slot) {
                selected.push({ name: sectors[idx].name, slot });
            }
        });

        if (selected.length === 0) {
            alert('No sectors selected.');
            return;
        }

        // Pre-flight: check all selected slots for existing data before fetching anything.
        const collisions = selected.filter(s => sectorSlotHasData(s.slot));
        if (collisions.length > 0) {
            const detail = collisions.map(c => `  • "${c.name}" → Slot ${c.slot}`).join('\n');
            alert(
                `The following sector slots already contain data.\n` +
                `Please clear each slot manually before importing:\n\n${detail}`
            );
            return;
        }

        closeModal();

        // Fetch and import one sector at a time with a 1-second pause between
        // each live API call to avoid hammering the travellermap API.
        const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));

        for (let i = 0; i < selected.length; i++) {
            const { name, slot } = selected[i];
            let fromCache = false;
            try {
                const cached = getCachedSector(name);
                fromCache = cached !== null;

                if (typeof showToast === 'function') {
                    const source = fromCache ? 'cache' : `API (${i + 1} of ${selected.length})`;
                    showToast(`Importing ${name} into Slot ${slot}… [${source}]`);
                }

                const text = fromCache ? cached : await fetchAndCacheSector(name);

                // Delegate to the existing T5 TSV parser with the user-specified slot.
                if (typeof importT5Tab === 'function') {
                    importT5Tab(text, name, slot);
                } else {
                    throw new Error('importT5Tab not available');
                }
            } catch (err) {
                alert(`Failed to import "${name}": ${err.message}`);
            }

            // Always pause 1 second after a live API call to respect travellermap rate limits.
            if (!fromCache && i < selected.length - 1) {
                await delay(1000);
            }
        }
    }

    // =========================================================================
    // IMPORT THE UNIVERSE
    // =========================================================================

    function getUniverseSectors() {
        if (!window.UNIVERSE_SECTORS || window.UNIVERSE_SECTORS.length === 0) {
            throw new Error('Universe sector list not loaded. Run convert_universe.ps1 to generate js/universe_data.js.');
        }
        return window.UNIVERSE_SECTORS;
    }

    /**
     * Bulk-imports every sector in UNIVERSE_SECTORS into a freshly resized 16×8 canvas.
     * Shows a warning confirmation first. Clears all existing data on proceed.
     */
    async function runUniverseImport() {
        let sectors;
        try {
            sectors = getUniverseSectors();
        } catch (err) {
            alert(`Cannot import: ${err.message}`);
            return;
        }

        const confirmed = confirm(
            '⚠ EXPERIMENTAL FEATURE — USE AT YOUR OWN RISK ⚠\n\n' +
            'Import the Universe will:\n' +
            '  • Resize the canvas to 16×8 sectors (128 positions)\n' +
            '  • Erase ALL existing hex data and routes\n' +
            `  • Fetch up to ${sectors.length} sectors from travellermap.com\n` +
            '    (cached sectors load instantly; live fetches are 1 second apart)\n\n' +
            'This cannot be undone.\n\n' +
            'Continue?'
        );
        if (!confirmed) return;

        // Resize canvas to 16×8 and clear all state.
        gridWidth  = 16;
        gridHeight = 8;
        hexStates.clear();
        window.sectorRoutes = [];
        window.undoStack    = [];
        window.redoStack    = [];

        centerCameraOnGrid();
        requestAnimationFrame(draw);

        const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));
        let errorCount = 0;

        for (let i = 0; i < sectors.length; i++) {
            const { name, defaultSlot } = sectors[i];
            let fromCache = false;
            try {
                const cached = getCachedSector(name);
                fromCache = cached !== null;

                if (typeof showToast === 'function') {
                    const source = fromCache ? 'cache' : `API (${i + 1} of ${sectors.length})`;
                    showToast(`Importing ${name} into Slot ${defaultSlot}… [${source}]`);
                }

                const text = fromCache ? cached : await fetchAndCacheSector(name);

                if (typeof importT5Tab === 'function') {
                    importT5Tab(text, name, defaultSlot);
                } else {
                    throw new Error('importT5Tab not available');
                }
            } catch (err) {
                console.warn(`[Universe Import] Failed to import "${name}": ${err.message}`);
                errorCount++;
            }

            if (!fromCache && i < sectors.length - 1) {
                await delay(1000);
            }
        }

        const summary = errorCount > 0
            ? `Universe import complete. ${errorCount} sector(s) failed — see console for details.`
            : `Universe import complete! ${sectors.length} sector(s) loaded.`;
        if (typeof showToast === 'function') showToast(summary, 4000);
    }

    /** Wire up all event listeners once the DOM is ready. */
    document.addEventListener('DOMContentLoaded', () => {
        // "Import the Imperium" settings button
        const btnImperium = document.getElementById('btn-import-imperium');
        if (btnImperium) {
            btnImperium.addEventListener('click', openImperiumModal);
        }

        // "Import the Universe" settings button
        const btnUniverse = document.getElementById('btn-import-universe');
        if (btnUniverse) {
            btnUniverse.addEventListener('click', runUniverseImport);
        }

        // Modal: Submit
        const btnSubmit = document.getElementById('otu-submit');
        if (btnSubmit) btnSubmit.addEventListener('click', runImport);

        // Modal: Cancel
        const btnCancel = document.getElementById('otu-cancel');
        if (btnCancel) btnCancel.addEventListener('click', closeModal);

        // Modal: Select / Deselect All
        const selectAll = document.getElementById('otu-select-all');
        if (selectAll) {
            selectAll.addEventListener('change', (e) => {
                document.querySelectorAll('.otu-sector-check').forEach(cb => {
                    cb.checked = e.target.checked;
                });
            });
        }

        // Close modal on backdrop click
        const modal = document.getElementById('otu-import-modal');
        if (modal) {
            modal.addEventListener('click', (e) => {
                if (e.target === modal) closeModal();
            });
        }
    });

    // Expose for debugging
    window.openImperiumModal = openImperiumModal;

}());
