/**
 * PROJECT AS ABOVE, SO BELOW
 * Module: OTU Importer
 * Description: Handles the "Import the Imperium" feature.
 *   - Loads the sector list from /sectors/imperium.tsv
 *   - Presents a modal for sector selection and slot assignment
 *   - Fetches each selected sector from the travellermap API
 *   - Feeds the result into the existing importT5Tab parser
 *
 * Sean Protocol: Zero RPG logic here. Pure orchestration and UI.
 */

(function () {
    'use strict';

    /**
     * Sector list is provided by js/imperium_data.js (auto-generated by convert_imperium.ps1).
     * Re-run convert_imperium.ps1 whenever sectors/imperium.tsv changes.
     */
    function getImperiumSectors() {
        if (!window.IMPERIUM_SECTORS || window.IMPERIUM_SECTORS.length === 0) {
            throw new Error('Sector list not loaded. Run convert_imperium.ps1 to generate js/imperium_data.js.');
        }
        return window.IMPERIUM_SECTORS;
    }

    /**
     * Returns true if a sector slot already contains non-empty hex data.
     * Used for the pre-flight collision check.
     */
    function sectorSlotHasData(slot) {
        const prefix = slot.toUpperCase() + '-';
        for (const [hexId, state] of hexStates) {
            if (hexId.startsWith(prefix) && state && state.type !== 'EMPTY') {
                return true;
            }
        }
        return false;
    }

    /**
     * Open the Import the Imperium modal.
     */
    function openImperiumModal() {
        try {
            renderModal(getImperiumSectors());
        } catch (err) {
            alert(`Failed to load sector list: ${err.message}`);
        }
    }

    /** Build and display the modal sector list. */
    function renderModal(sectors) {
        const list = document.getElementById('otu-sector-list');
        list.innerHTML = '';

        sectors.forEach((sector, idx) => {
            const row = document.createElement('label');
            row.className = 'otu-sector-row';
            row.style.cssText = [
                'display:flex', 'align-items:center', 'gap:8px',
                'padding:6px 10px', 'border-radius:4px',
                'border-left:3px solid transparent',
                'cursor:pointer', 'transition:background 0.15s, border-color 0.15s',
                'background:#0d1117'
            ].join(';');

            row.innerHTML = `
                <input type="checkbox" class="otu-sector-check" data-idx="${idx}" checked
                    style="flex-shrink:0; cursor:pointer; accent-color:#66fcf1;">
                <span class="otu-sector-name"
                    style="color:#c5c6c7; font-size:0.85rem; white-space:nowrap;">${sector.name}</span>
                <span style="flex:1; border-bottom:1px dotted #2a3a3a; margin:0 4px; height:1px; align-self:center;"></span>
                <input type="text" class="otu-sector-slot" value="${sector.defaultSlot}"
                    maxlength="2" size="2"
                    style="width:32px; padding:2px 4px; background:#1f2833; border:1px solid #45a29e;
                           color:#66fcf1; font-family:'Courier New',monospace; font-size:0.85rem;
                           text-align:center; text-transform:uppercase; border-radius:3px;"
                    onclick="event.stopPropagation();">
            `;

            // Highlight row on hover
            row.addEventListener('mouseenter', () => {
                row.style.background = '#1a2535';
                row.style.borderLeftColor = '#45a29e';
            });
            row.addEventListener('mouseleave', () => {
                row.style.background = '#0d1117';
                row.style.borderLeftColor = 'transparent';
            });

            list.appendChild(row);
        });

        // Reset select-all to checked
        const selectAll = document.getElementById('otu-select-all');
        if (selectAll) selectAll.checked = true;

        document.getElementById('otu-import-modal').style.display = 'flex';
    }

    /** Close the modal. */
    function closeModal() {
        document.getElementById('otu-import-modal').style.display = 'none';
    }

    /**
     * Pre-flight check, then fetch and import each selected sector in sequence.
     */
    async function runImport() {
        const rows = document.querySelectorAll('.otu-sector-row');
        const selected = [];

        const sectors = getImperiumSectors();
        rows.forEach((row, idx) => {
            const cb = row.querySelector('.otu-sector-check');
            const slotInput = row.querySelector('.otu-sector-slot');
            const slot = (slotInput ? slotInput.value.trim() : '').toUpperCase();
            if (cb && cb.checked && slot) {
                selected.push({ name: sectors[idx].name, slot });
            }
        });

        if (selected.length === 0) {
            alert('No sectors selected.');
            return;
        }

        // Pre-flight: check all selected slots for existing data before fetching anything.
        const collisions = selected.filter(s => sectorSlotHasData(s.slot));
        if (collisions.length > 0) {
            const detail = collisions.map(c => `  • "${c.name}" → Slot ${c.slot}`).join('\n');
            alert(
                `The following sector slots already contain data.\n` +
                `Please clear each slot manually before importing:\n\n${detail}`
            );
            return;
        }

        closeModal();

        // Fetch and import one sector at a time with a 1-second pause between
        // each call to avoid hammering the travellermap API.
        const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));

        for (let i = 0; i < selected.length; i++) {
            const { name, slot } = selected[i];
            try {
                if (typeof showToast === 'function') showToast(`Importing ${name} into Slot ${slot}… (${i + 1} of ${selected.length})`);

                const url = `https://travellermap.com/data/${encodeURIComponent(name)}/tab`;
                const response = await fetch(url);
                if (!response.ok) throw new Error(`HTTP ${response.status}`);
                const text = await response.text();

                // Delegate to the existing T5 TSV parser with the user-specified slot.
                if (typeof importT5Tab === 'function') {
                    importT5Tab(text, name, slot);
                } else {
                    throw new Error('importT5Tab not available');
                }
            } catch (err) {
                alert(`Failed to import "${name}": ${err.message}`);
            }

            // Pause before the next request (skip delay after the last sector).
            if (i < selected.length - 1) await delay(1000);
        }
    }

    /** Wire up all event listeners once the DOM is ready. */
    document.addEventListener('DOMContentLoaded', () => {
        // "Import the Imperium" settings button
        const btnImperium = document.getElementById('btn-import-imperium');
        if (btnImperium) {
            btnImperium.addEventListener('click', openImperiumModal);
        }

        // Modal: Submit
        const btnSubmit = document.getElementById('otu-submit');
        if (btnSubmit) btnSubmit.addEventListener('click', runImport);

        // Modal: Cancel
        const btnCancel = document.getElementById('otu-cancel');
        if (btnCancel) btnCancel.addEventListener('click', closeModal);

        // Modal: Select / Deselect All
        const selectAll = document.getElementById('otu-select-all');
        if (selectAll) {
            selectAll.addEventListener('change', (e) => {
                document.querySelectorAll('.otu-sector-check').forEach(cb => {
                    cb.checked = e.target.checked;
                });
            });
        }

        // Close modal on backdrop click
        const modal = document.getElementById('otu-import-modal');
        if (modal) {
            modal.addEventListener('click', (e) => {
                if (e.target === modal) closeModal();
            });
        }
    });

    // Expose for debugging
    window.openImperiumModal = openImperiumModal;

}());
