/**
 * PROJECT AS ABOVE, SO BELOW
 * Module: OTU Importer
 * Description: Handles the "Import the Imperium" feature.
 *   - Loads the sector list from /sectors/imperium.tsv
 *   - Presents a modal for sector selection and slot assignment
 *   - Fetches each selected sector from the travellermap API
 *   - Feeds the result into the existing importT5Tab parser
 *
 * Sean Protocol: Zero RPG logic here. Pure orchestration and UI.
 */

(function () {
    'use strict';

    /**
     * Sector list is provided by js/imperium_data.js (auto-generated by convert_imperium.ps1).
     * Re-run convert_imperium.ps1 whenever sectors/imperium.tsv changes.
     */
    function getImperiumSectors() {
        if (!window.IMPERIUM_SECTORS || window.IMPERIUM_SECTORS.length === 0) {
            throw new Error('Sector list not loaded. Run convert_imperium.ps1 to generate js/imperium_data.js.');
        }
        return window.IMPERIUM_SECTORS;
    }

    const CACHE_PREFIX = 'otu_cache_';
    const META_PREFIX  = 'otu_meta_';
    const CACHE_TTL_MS = 24 * 60 * 60 * 1000; // 24 hours

    // Derive the travellermap slug for metadata URLs:
    //   1. Strip leading "The " (case-insensitive)
    //   2. Remove all non-alphanumeric characters
    //   3. Take first 4 chars, lowercase
    function sectorMetadataSlug(name) {
        return name
            .replace(/^the\s+/i, '')
            .replace(/[^a-z0-9]/gi, '')
            .slice(0, 4)
            .toLowerCase();
    }

    /**
     * Returns cached TSV text for a sector if it exists and is less than 24 hours old.
     * Returns null on a miss, an expired entry, or any storage error.
     */
    function getCachedSector(name) {
        try {
            const raw = localStorage.getItem(CACHE_PREFIX + name);
            if (!raw) return null;
            const entry = JSON.parse(raw);
            if (!entry || !entry.timestamp || !entry.data) return null;
            if (Date.now() - entry.timestamp > CACHE_TTL_MS) return null;
            return entry.data;
        } catch (e) {
            return null;
        }
    }

    /**
     * Fetches raw TSV text for a sector from the travellermap API.
     * Throws on HTTP error. Shared by both cache paths.
     */
    async function fetchSectorText(name) {
        const url = `https://travellermap.com/data/${encodeURIComponent(name)}/tab`;
        const response = await fetch(url);
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
        return await response.text();
    }

    /**
     * Fetches a sector, writes it to localStorage, and returns the TSV text.
     * Used by the Imperium import (small number of sectors, fits in localStorage).
     * Silently skips the cache write on QuotaExceededError so import still completes.
     */
    async function fetchAndCacheSector(name) {
        const text = await fetchSectorText(name);
        try {
            localStorage.setItem(CACHE_PREFIX + name, JSON.stringify({
                timestamp: Date.now(),
                data: text
            }));
        } catch (e) {
            console.warn(`[OTU Importer] Could not cache "${name}": ${e.message}`);
        }
        return text;
    }

    /**
     * Reads a universe sector TSV from IndexedDB. Returns the text string or null
     * on a miss, expiry, or if dbManager is unavailable.
     */
    async function getCachedUniverseSector(name) {
        if (!window.dbManager) return null;
        const entry = await window.dbManager.getTsvCache(name);
        if (!entry || !entry.data || !entry.timestamp) return null;
        if (Date.now() - entry.timestamp > CACHE_TTL_MS) return null;
        return entry.data;
    }

    /**
     * Fetches a sector, writes it to the IndexedDB TSV cache, and returns the text.
     * Used by the Universe import (128 sectors, exceeds localStorage quota).
     */
    async function fetchAndCacheUniverseSector(name) {
        const text = await fetchSectorText(name);
        if (window.dbManager) await window.dbManager.putTsvCache(name, text);
        return text;
    }

    /**
     * Returns cached metadata XML for a sector, or null on miss/expiry.
     */
    function getCachedMetadata(name) {
        try {
            const raw = localStorage.getItem(META_PREFIX + name);
            if (!raw) return null;
            const entry = JSON.parse(raw);
            if (!entry || !entry.timestamp || !entry.data) return null;
            if (Date.now() - entry.timestamp > CACHE_TTL_MS) return null;
            return entry.data;
        } catch (e) {
            return null;
        }
    }

    /**
     * Fetches sector metadata XML from travellermap, caches it, and returns the raw text.
     * Non-fatal: logs a warning and returns null on HTTP error so the import continues.
     */
    async function fetchAndCacheMetadata(name) {
        const slug = sectorMetadataSlug(name);
        const url  = `https://travellermap.com/data/${encodeURIComponent(slug)}/metadata`;
        let text;
        try {
            const response = await fetch(url);
            if (!response.ok) {
                console.warn(`[OTU Importer] Metadata fetch failed for "${name}" (slug: ${slug}): HTTP ${response.status}`);
                return null;
            }
            text = await response.text();
        } catch (e) {
            console.warn(`[OTU Importer] Metadata fetch error for "${name}": ${e.message}`);
            return null;
        }
        try {
            localStorage.setItem(META_PREFIX + name, JSON.stringify({
                timestamp: Date.now(),
                data: text
            }));
        } catch (e) {
            console.warn(`[OTU Importer] Could not cache metadata for "${name}": ${e.message}`);
        }
        return text;
    }

    /**
     * Reads universe metadata XML from IndexedDB. Returns text or null.
     * Keyed as 'meta:<name>' inside the shared tsvCache store.
     */
    async function getCachedUniverseMetadata(name) {
        if (!window.dbManager) return null;
        const entry = await window.dbManager.getTsvCache('meta:' + name);
        if (!entry || !entry.data || !entry.timestamp) return null;
        if (Date.now() - entry.timestamp > CACHE_TTL_MS) return null;
        return entry.data;
    }

    /**
     * Fetches sector metadata XML and writes it to IndexedDB.
     * Non-fatal: logs a warning and returns null on HTTP error.
     */
    async function fetchAndCacheUniverseMetadata(name) {
        const slug = sectorMetadataSlug(name);
        const url  = `https://travellermap.com/data/${encodeURIComponent(slug)}/metadata`;
        let text;
        try {
            const response = await fetch(url);
            if (!response.ok) {
                console.warn(`[OTU Importer] Metadata fetch failed for "${name}" (slug: ${slug}): HTTP ${response.status}`);
                return null;
            }
            text = await response.text();
        } catch (e) {
            console.warn(`[OTU Importer] Metadata fetch error for "${name}": ${e.message}`);
            return null;
        }
        if (window.dbManager) await window.dbManager.putTsvCache('meta:' + name, text);
        return text;
    }

    /**
     * Returns true if a sector slot already contains non-empty hex data.
     * Used for the pre-flight collision check.
     */
    function sectorSlotHasData(slot) {
        // Convert slot label to numeric sector ID so the prefix matches
        // the numeric hexId format used since the v0.7.3 refactor.
        const num = sectorSlotToNumber(slot);
        const prefix = num + '-';
        for (const [hexId, state] of hexStates) {
            if (hexId.startsWith(prefix) && state && state.type !== 'EMPTY') {
                return true;
            }
        }
        return false;
    }

    /**
     * Open the Import the Imperium modal.
     */
    function openImperiumModal() {
        try {
            renderModal(getImperiumSectors());
        } catch (err) {
            alert(`Failed to load sector list: ${err.message}`);
        }
    }

    /** Build and display the modal sector list. */
    function renderModal(sectors) {
        const list = document.getElementById('otu-sector-list');
        list.innerHTML = '';

        sectors.forEach((sector, idx) => {
            const row = document.createElement('label');
            row.className = 'otu-sector-row';
            row.style.cssText = [
                'display:flex', 'align-items:center', 'gap:8px',
                'padding:6px 10px', 'border-radius:4px',
                'border-left:3px solid transparent',
                'cursor:pointer', 'transition:background 0.15s, border-color 0.15s',
                'background:#0d1117'
            ].join(';');

            row.innerHTML = `
                <input type="checkbox" class="otu-sector-check" data-idx="${idx}" checked
                    style="flex-shrink:0; cursor:pointer; accent-color:#66fcf1;">
                <span class="otu-sector-name"
                    style="color:#c5c6c7; font-size:0.85rem; white-space:nowrap;">${sector.name}</span>
                <span style="flex:1; border-bottom:1px dotted #2a3a3a; margin:0 4px; height:1px; align-self:center;"></span>
                <input type="text" class="otu-sector-slot" value="${sector.defaultSlot}"
                    maxlength="2" size="2"
                    style="width:32px; padding:2px 4px; background:#1f2833; border:1px solid #45a29e;
                           color:#66fcf1; font-family:'Courier New',monospace; font-size:0.85rem;
                           text-align:center; text-transform:uppercase; border-radius:3px;"
                    onclick="event.stopPropagation();">
            `;

            // Highlight row on hover
            row.addEventListener('mouseenter', () => {
                row.style.background = '#1a2535';
                row.style.borderLeftColor = '#45a29e';
            });
            row.addEventListener('mouseleave', () => {
                row.style.background = '#0d1117';
                row.style.borderLeftColor = 'transparent';
            });

            list.appendChild(row);
        });

        // Reset select-all to checked
        const selectAll = document.getElementById('otu-select-all');
        if (selectAll) selectAll.checked = true;

        document.getElementById('otu-import-modal').style.display = 'flex';
    }

    /** Close the modal. */
    function closeModal() {
        document.getElementById('otu-import-modal').style.display = 'none';
    }

    /**
     * Pre-flight check, then fetch and import each selected sector in sequence.
     */
    async function runImport() {
        const rows = document.querySelectorAll('.otu-sector-row');
        const selected = [];

        const sectors = getImperiumSectors();
        rows.forEach((row, idx) => {
            const cb = row.querySelector('.otu-sector-check');
            const slotInput = row.querySelector('.otu-sector-slot');
            const slot = (slotInput ? slotInput.value.trim() : '').toUpperCase();
            if (cb && cb.checked && slot) {
                selected.push({ name: sectors[idx].name, slot });
            }
        });

        if (selected.length === 0) {
            alert('No sectors selected.');
            return;
        }

        // Pre-flight: check all selected slots for existing data before fetching anything.
        const collisions = selected.filter(s => sectorSlotHasData(s.slot));
        if (collisions.length > 0) {
            const detail = collisions.map(c => `  • "${c.name}" → Slot ${c.slot}`).join('\n');
            alert(
                `The following sector slots already contain data.\n` +
                `Please clear each slot manually before importing:\n\n${detail}`
            );
            return;
        }

        closeModal();

        // Fetch and import one sector at a time. Each sector makes two API calls
        // (TSV then metadata) with a 1-second pause between each live call.
        const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));

        // Build coord lookup for cross-sector route resolution.
        // Only include sectors the user actually imported — pre-loading all sectors
        // caused routes to unimported neighbours to resolve to wrong hexIds on canvas.
        const coordLookup = new Map();
        selected.forEach(sel => {
            const match = sectors.find(s => s.name === sel.name);
            if (match) coordLookup.set(`${match.x},${match.y}`, sectorSlotToNumber(sel.slot));
        });

        const sectorMetas = [];
        for (let i = 0; i < selected.length; i++) {
            const { name, slot } = selected[i];
            let tsvFromCache = false;
            try {
                const cached = getCachedSector(name);
                tsvFromCache = cached !== null;

                if (typeof showToast === 'function') {
                    const source = tsvFromCache ? 'cache' : `API (${i + 1} of ${selected.length})`;
                    showToast(`Importing ${name} into Slot ${slot}… [${source}]`);
                }

                const text = tsvFromCache ? cached : await fetchAndCacheSector(name);

                // Delegate to the existing T5 TSV parser with the user-specified slot.
                if (typeof importT5Tab === 'function') {
                    importT5Tab(text, name, slot);
                } else {
                    throw new Error('importT5Tab not available');
                }

                // Store sector name — preserve any existing manual name (conflict rule)
                const slotNum = parseInt(slot, 10);
                if (!isNaN(slotNum) && !window.sectorNames[slotNum]) {
                    window.sectorNames[slotNum] = name;
                }
            } catch (err) {
                alert(`Failed to import "${name}": ${err.message}`);
            }

            // Pause before metadata fetch if TSV came from a live API call.
            if (!tsvFromCache) await delay(1000);

            // Fetch and cache metadata now, but defer route parsing until all sectors are loaded.
            let metaXml = getCachedMetadata(name);
            if (!metaXml) {
                if (typeof showToast === 'function') showToast(`Fetching metadata for ${name}…`);
                metaXml = await fetchAndCacheMetadata(name);
                if (i < selected.length - 1) await delay(1000);
            }
            const sectorInfo = sectors.find(s => s.name === name);
            if (metaXml && sectorInfo) {
                sectorMetas.push({ name, metaXml, slotNum: sectorSlotToNumber(slot), x: sectorInfo.x, y: sectorInfo.y });
            }
        }

        // Parse all routes in a single pass after every sector is loaded,
        // so cross-sector routes can resolve both endpoints correctly.
        if (typeof parseAndAddOtuRoutes === 'function') {
            for (const m of sectorMetas) {
                parseAndAddOtuRoutes(m.name, m.metaXml, m.slotNum, m.x, m.y, coordLookup);
            }
        }

        requestAnimationFrame(draw);
    }

    // =========================================================================
    // IMPORT THE UNIVERSE
    // =========================================================================

    function getUniverseSectors() {
        if (!window.UNIVERSE_SECTORS || window.UNIVERSE_SECTORS.length === 0) {
            throw new Error('Universe sector list not loaded. Run convert_universe.ps1 to generate js/universe_data.js.');
        }
        return window.UNIVERSE_SECTORS;
    }

    /**
     * Bulk-imports every sector in UNIVERSE_SECTORS into a freshly resized 16×8 canvas.
     * Shows a warning confirmation first. Clears all existing data on proceed.
     */
    async function runUniverseImport() {
        let sectors;
        try {
            sectors = getUniverseSectors();
        } catch (err) {
            alert(`Cannot import: ${err.message}`);
            return;
        }

        const confirmed = confirm(
            '⚠ EXPERIMENTAL FEATURE — USE AT YOUR OWN RISK ⚠\n\n' +
            'Import the Universe will:\n' +
            '  • Resize the canvas to 16×8 sectors (128 positions)\n' +
            '  • Erase ALL existing hex data and routes\n' +
            `  • Fetch up to ${sectors.length} sectors from travellermap.com\n` +
            '    (cached sectors load instantly; live fetches are 1 second apart)\n\n' +
            'This cannot be undone.\n\n' +
            'Continue?'
        );
        if (!confirmed) return;

        // Wipe IndexedDB before clearing memory so no stale data remains.
        if (window.dbManager) await window.dbManager.clearDB();

        // Resize canvas to 16×8 and clear all in-memory state.
        gridWidth  = 16;
        gridHeight = 8;
        hexStates.clear();
        window.sectorRoutes = [];
        window.undoStack    = [];
        window.redoStack    = [];

        centerCameraOnGrid();
        requestAnimationFrame(draw);

        // Persist the new grid dimensions immediately.
        if (window.dbManager) window.dbManager.saveGridDimensions();

        const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));
        let errorCount = 0;

        // Build coord lookup from all universe sectors using their default slots.
        const coordLookup = new Map();
        sectors.forEach(s => coordLookup.set(`${s.x},${s.y}`, parseInt(s.defaultSlot, 10)));

        const universeMetas = [];
        for (let i = 0; i < sectors.length; i++) {
            const { name, defaultSlot, x, y } = sectors[i];
            let tsvFromCache = false;
            try {
                const cached = await getCachedUniverseSector(name);
                tsvFromCache = cached !== null;

                if (typeof showToast === 'function') {
                    const source = tsvFromCache ? 'cache' : `API (${i + 1} of ${sectors.length})`;
                    showToast(`Importing ${name} into Slot ${defaultSlot}… [${source}]`);
                }

                const text = tsvFromCache ? cached : await fetchAndCacheUniverseSector(name);

                if (typeof importT5Tab === 'function') {
                    importT5Tab(text, name, defaultSlot);
                } else {
                    throw new Error('importT5Tab not available');
                }

                // Store sector name — preserve any existing manual name (conflict rule)
                const slotNum = parseInt(defaultSlot, 10);
                if (!isNaN(slotNum) && !window.sectorNames[slotNum]) {
                    window.sectorNames[slotNum] = name;
                }
            } catch (err) {
                console.warn(`[Universe Import] Failed to import "${name}": ${err.message}`);
                errorCount++;
            }

            // Pause before metadata fetch if TSV came from a live API call.
            if (!tsvFromCache) await delay(1000);

            // Fetch and cache metadata, but defer route parsing until all sectors are loaded.
            let metaXml = await getCachedUniverseMetadata(name);
            if (!metaXml) {
                if (typeof showToast === 'function') showToast(`Fetching metadata for ${name}…`);
                metaXml = await fetchAndCacheUniverseMetadata(name);
                if (i < sectors.length - 1) await delay(1000);
            }
            if (metaXml) {
                universeMetas.push({ name, metaXml, slotNum: parseInt(defaultSlot, 10), x, y });
            }
        }

        // Parse all routes in a single pass after every sector is loaded,
        // so cross-sector routes can resolve both endpoints correctly.
        if (typeof parseAndAddOtuRoutes === 'function') {
            for (const m of universeMetas) {
                parseAndAddOtuRoutes(m.name, m.metaXml, m.slotNum, m.x, m.y, coordLookup);
            }
        }

        requestAnimationFrame(draw);

        const summary = errorCount > 0
            ? `Universe import complete. ${errorCount} sector(s) failed — see console for details.`
            : `Universe import complete! ${sectors.length} sector(s) loaded.`;
        if (typeof showToast === 'function') showToast(summary, 4000);
    }

    /** Wire up all event listeners once the DOM is ready. */
    document.addEventListener('DOMContentLoaded', () => {
        // "Import the Imperium" settings button
        const btnImperium = document.getElementById('btn-import-imperium');
        if (btnImperium) {
            btnImperium.addEventListener('click', openImperiumModal);
        }

        // "Import the Universe" settings button
        const btnUniverse = document.getElementById('btn-import-universe');
        if (btnUniverse) {
            btnUniverse.addEventListener('click', runUniverseImport);
        }

        // Modal: Submit
        const btnSubmit = document.getElementById('otu-submit');
        if (btnSubmit) btnSubmit.addEventListener('click', runImport);

        // Modal: Cancel
        const btnCancel = document.getElementById('otu-cancel');
        if (btnCancel) btnCancel.addEventListener('click', closeModal);

        // Modal: Select / Deselect All
        const selectAll = document.getElementById('otu-select-all');
        if (selectAll) {
            selectAll.addEventListener('change', (e) => {
                document.querySelectorAll('.otu-sector-check').forEach(cb => {
                    cb.checked = e.target.checked;
                });
            });
        }

        // Close modal on backdrop click
        const modal = document.getElementById('otu-import-modal');
        if (modal) {
            modal.addEventListener('click', (e) => {
                if (e.target === modal) closeModal();
            });
        }
    });

    // Expose for debugging
    window.openImperiumModal = openImperiumModal;

}());
