# convert_imperium.ps1
# Converts sectors/imperium.tsv into js/imperium_data.js for loading in hex_map.html
# Run this script whenever you add sectors to imperium.tsv

# Use MyInvocation so the script finds its own directory regardless of how it is launched
$scriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Definition
$inputFile  = Join-Path $scriptDir "sectors\imperium.tsv"
$outputFile = Join-Path $scriptDir "js\imperium_data.js"

if (-not (Test-Path $inputFile)) {
    Write-Host "ERROR: imperium.tsv not found at $inputFile"
    exit 1
}

Write-Host "Reading $inputFile ..."

# Read all lines via .NET — no pipeline, no encoding ambiguity
$lines = [System.IO.File]::ReadAllLines($inputFile)

$jsonItems = [System.Collections.Generic.List[string]]::new()

for ($i = 1; $i -lt $lines.Length; $i++) {
    $line = $lines[$i].Trim()
    if ($line -eq '') { continue }

    $parts = $line -split "`t"
    if ($parts.Length -ge 2 -and $parts[0].Trim() -ne '') {
        $name = $parts[0].Trim().Replace('"', '\"')
        $slot = $parts[1].Trim().Replace('"', '\"')
        $jsonItems.Add("{`"name`":`"$name`",`"defaultSlot`":`"$slot`"}")
    }
}

$json    = "[" + [string]::Join(",", $jsonItems) + "]"
$content = "// Auto-generated by convert_imperium.ps1 - do not edit manually.`n// Re-run the script whenever sectors/imperium.tsv changes.`nwindow.IMPERIUM_SECTORS = $json;"

[System.IO.File]::WriteAllText($outputFile, $content, [System.Text.Encoding]::UTF8)

Write-Host "Done! Wrote js/imperium_data.js ($($jsonItems.Count) sector(s))"
