# convert_names.ps1
# Converts names.csv into names.js for automatic loading in hex_map.html
# Run this script once whenever you update names.csv

$inputFile  = Join-Path $PSScriptRoot "names.csv"
$outputFile = Join-Path $PSScriptRoot "names.js"

if (-not (Test-Path $inputFile)) {
    Write-Error "names.csv not found at $inputFile"
    exit 1
}

$names = [System.Collections.Generic.List[string]]::new()
$seen  = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)

Get-Content $inputFile -Encoding UTF8 | ForEach-Object {
    $line = $_.Trim()
    if (-not $line) { return }

    # Take first column, strip surrounding quotes
    $raw = ($line -split ',')[0].Trim().Trim('"')

    # Strip non-ASCII characters (anything outside 0x20-0x7E printable range)
    $cleaned = [System.Text.RegularExpressions.Regex]::Replace($raw, '[^\x20-\x7E]', '')
    # Keep only letters, digits, spaces, hyphens, apostrophes
    $cleaned = [System.Text.RegularExpressions.Regex]::Replace($cleaned, "[^a-zA-Z0-9 \-']", '').Trim()

    # Truncate to 25 characters
    if ($cleaned.Length -gt 25) { $cleaned = $cleaned.Substring(0, 25).TrimEnd() }

    if ($cleaned.Length -gt 0 -and $seen.Add($cleaned)) {
        $names.Add($cleaned)
    }
}

$jsonLines = $names | ForEach-Object { "  `"$($_ -replace '"', '\"')`"" }
$jsonArray = $jsonLines -join ",`n"

$output = @"
// Auto-generated by convert_names.ps1 - do not edit manually.
// Re-run the script whenever names.csv changes.
window.SYSTEM_NAMES = [
$jsonArray
];
"@

Set-Content -Path $outputFile -Value $output -Encoding UTF8
Write-Host "Done! Wrote $($names.Count) names to names.js"
