# convert_universe.ps1
# Fetches OTU sector list from the travellermap API and generates js/universe_data.js.
# Covers the full 16x8 canvas:
#   X: -8 (Sidiadl/spinward edge) to  7 (Treece/trailing edge)
#   Y: -3 (coreward edge)         to  4 (rimward edge)
#
# Re-run whenever you need fresh data from travellermap.

$scriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Definition
$outputFile = Join-Path $scriptDir "js\universe_data.js"

# ---- Grid bounds (must match the 16x8 Universe canvas) ----
# Y in travellermap coords: negative = coreward (up), positive = rimward (down)
# Top-left:     Sidiadl  (-8, -3)   Bottom-right: Treece (7, 4)
$X_MIN  = -8
$X_MAX  =  7
$Y_MIN  = -3
$Y_MAX  =  4
$GRID_W = 16   # columns in the Universe canvas

Write-Host "Fetching sector list from travellermap.com/api/universe ..."

# milieu=M1105 restricts to the standard Third Imperium 1105 dataset,
# preventing duplicate entries for sectors that exist in other milieus.
try {
    $data = Invoke-RestMethod -Uri "https://travellermap.com/api/universe?milieu=M1105" -TimeoutSec 30
} catch {
    Write-Host "ERROR: API call failed: $_"
    exit 1
}

# The API wraps sectors under different keys depending on the response shape.
$allSectors = $null
if ($data.Sectors)                              { $allSectors = $data.Sectors }
elseif ($data.Universe -and $data.Universe.Sectors) { $allSectors = $data.Universe.Sectors }

if (-not $allSectors) {
    Write-Host "ERROR: Could not locate Sectors array in response."
    Write-Host "Top-level keys: $($data.PSObject.Properties.Name -join ', ')"
    exit 1
}

Write-Host "Universe contains $($allSectors.Count) total sector(s)."
Write-Host "Filtering to X:[$X_MIN, $X_MAX] Y:[$Y_MIN, $Y_MAX] ..."

$jsonItems = [System.Collections.Generic.List[string]]::new()

# Collect matching sectors, deduplicating by (X, Y).
$seen    = [System.Collections.Generic.HashSet[string]]::new()
$matched = [System.Collections.Generic.List[object]]::new()
foreach ($sector in $allSectors) {
    $sx  = [int]$sector.X
    $sy  = [int]$sector.Y
    $key = "$sx,$sy"
    if ($sx -ge $X_MIN -and $sx -le $X_MAX -and $sy -ge $Y_MIN -and $sy -le $Y_MAX) {
        if ($seen.Add($key)) {
            $matched.Add($sector)
        }
    }
}

# Sort in reading order (Y ascending, then X ascending).
$matchedArray = $matched | Sort-Object { [int]$_.Y }, { [int]$_.X }

foreach ($sector in $matchedArray) {
    # Resolve the primary English name.
    $name = ""
    if ($sector.Names -and $sector.Names.Count -gt 0) {
        $name = $sector.Names[0].Text
    } elseif ($sector.Name) {
        $name = $sector.Name
    }
    if ($name -eq "") { continue }

    $sx = [int]$sector.X
    $sy = [int]$sector.Y

    # Compute 1-based slot number for the 16x8 grid.
    $col  = $sx - $X_MIN
    $row  = $sy - $Y_MIN
    $slot = $row * $GRID_W + $col + 1

    $nameSafe = $name.Replace('\', '\\').Replace('"', '\"')
    $jsonItems.Add("{`"name`":`"$nameSafe`",`"x`":$sx,`"y`":$sy,`"defaultSlot`":`"$slot`"}")

    Write-Host ("  Slot {0,3}  ({1,3},{2,3})  {3}" -f $slot, $sx, $sy, $name)
}

if ($jsonItems.Count -eq 0) {
    Write-Host "ERROR: No sectors matched the grid bounds. Check API response format."
    exit 1
}

$json    = "[" + [string]::Join(",", $jsonItems) + "]"
$content = "// Auto-generated by convert_universe.ps1 - do not edit manually.`n"
$content += "// Source: travellermap.com/api/universe  Grid: X[$X_MIN,$X_MAX] Y[$Y_MIN,$Y_MAX] (16x8)`n"
$content += "window.UNIVERSE_SECTORS = $json;"

[System.IO.File]::WriteAllText($outputFile, $content, [System.Text.Encoding]::UTF8)

Write-Host ""
Write-Host "Done! Wrote js/universe_data.js ($($jsonItems.Count) sector(s))."
