# convert_foreven_mixon.ps1
# Converts sectors/foreven_mixon.tsv and sectors/foreven_mixon.xml into
# js/foreven_mixon_data.js for loading in hex_map.html.
# Re-run this script whenever either source file changes.

$tsvFile    = Join-Path $PSScriptRoot "sectors\foreven_mixon.tsv"
$xmlFile    = Join-Path $PSScriptRoot "sectors\foreven_mixon.xml"
$outputFile = Join-Path $PSScriptRoot "js\foreven_mixon_data.js"

if (-not (Test-Path $tsvFile)) {
    Write-Error "foreven_mixon.tsv not found at $tsvFile"
    exit 1
}
if (-not (Test-Path $xmlFile)) {
    Write-Error "foreven_mixon.xml not found at $xmlFile"
    exit 1
}

Write-Host "Reading $tsvFile ..."
$tsvContent = Get-Content $tsvFile -Raw -Encoding UTF8

Write-Host "Reading $xmlFile ..."
$xmlContent = Get-Content $xmlFile -Raw -Encoding UTF8

# Cast to [string] to strip PowerShell ETS metadata before converting to JSON,
# otherwise ConvertTo-Json serializes hidden properties (PSPath, etc.) into an object.
$tsvJson = ConvertTo-Json ([string]$tsvContent)
$xmlJson = ConvertTo-Json ([string]$xmlContent)

$output = @"
// Auto-generated by convert_foreven_mixon.ps1 - do not edit manually.
// Re-run the script whenever sectors/foreven_mixon.tsv or sectors/foreven_mixon.xml changes.
window.FOREVEN_MIXON_TSV = $tsvJson;
window.FOREVEN_MIXON_XML = $xmlJson;
"@

Set-Content -Path $outputFile -Value $output -Encoding UTF8
Write-Host "Done! Wrote js/foreven_mixon_data.js"
