# convert_solo6.ps1
# Converts sectors/solo_6.json into js/solo_6_data.js for automatic loading in hex_map.html
# Run this script whenever you regenerate solo_6.json

$inputFile  = Join-Path $PSScriptRoot "sectors\solo_6.json"
$outputFile = Join-Path $PSScriptRoot "js\solo_6_data.js"

if (-not (Test-Path $inputFile)) {
    Write-Error "solo_6.json not found at $inputFile"
    exit 1
}

Write-Host "Reading $inputFile ..."
$jsonContent = Get-Content $inputFile -Raw -Encoding UTF8

$output = @"
// Auto-generated by convert_solo6.ps1 - do not edit manually.
// Re-run the script whenever sectors/solo_6.json changes.
window.SOLO_6_DATA = $jsonContent;
"@

Set-Content -Path $outputFile -Value $output -Encoding UTF8
Write-Host "Done! Wrote js/solo_6_data.js"
