# convert_imperium.ps1
# Fetches OTU sector list from the travellermap API and generates js/imperium_data.js.
# Only includes sectors whose coordinates fall within the 7x5 Imperium grid:
#   X: -4 (Spinward Marches) to 2 (Spica)
#   Y: -1 (top row) to 3 (bottom row)
#
# Re-run whenever you need fresh data from travellermap.

$scriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Definition
$outputFile = Join-Path $scriptDir "js\imperium_data.js"

# ---- Grid bounds (must match the 7x5 default canvas) ----
$X_MIN  = -4
$X_MAX  =  2
$Y_MIN  = -1
$Y_MAX  =  3
$GRID_W =  7   # columns in the default canvas

Write-Host "Fetching sector list from travellermap.com/api/universe ..."

# milieu=M1105 restricts to the standard Third Imperium 1105 dataset,
# preventing duplicate entries for sectors that also exist in other milieus.
try {
    $data = Invoke-RestMethod -Uri "https://travellermap.com/api/universe?milieu=M1105" -TimeoutSec 30
} catch {
    Write-Host "ERROR: API call failed: $_"
    exit 1
}

# The API wraps sectors under different keys depending on the response shape.
# Try the two most common layouts.
$allSectors = $null
if ($data.Sectors)                   { $allSectors = $data.Sectors }
elseif ($data.Universe -and $data.Universe.Sectors) { $allSectors = $data.Universe.Sectors }

if (-not $allSectors) {
    Write-Host "ERROR: Could not locate Sectors array in response."
    Write-Host "Top-level keys: $($data.PSObject.Properties.Name -join ', ')"
    exit 1
}

Write-Host "Universe contains $($allSectors.Count) total sector(s)."
Write-Host "Filtering to X:[$X_MIN, $X_MAX] Y:[$Y_MIN, $Y_MAX] ..."

$jsonItems = [System.Collections.Generic.List[string]]::new()

# Collect matching sectors, deduplicating by (X, Y) in case the API returns
# multiple entries for the same coordinate (e.g. alternate-milieu echoes).
$seen    = [System.Collections.Generic.HashSet[string]]::new()
$matched = [System.Collections.Generic.List[object]]::new()
foreach ($sector in $allSectors) {
    $sx  = [int]$sector.X
    $sy  = [int]$sector.Y
    $key = "$sx,$sy"
    if ($sx -ge $X_MIN -and $sx -le $X_MAX -and $sy -ge $Y_MIN -and $sy -le $Y_MAX) {
        if ($seen.Add($key)) {   # Add() returns false if already present
            $matched.Add($sector)
        }
    }
}

# Sort in reading order (Y ascending, then X ascending).
# Sort-Object is safe here — only ~28 sectors, no pipeline-stall risk.
$matchedArray = $matched | Sort-Object { [int]$_.Y }, { [int]$_.X }

foreach ($sector in $matchedArray) {
    # Resolve the primary English name — try Names array first, then Name string.
    $name = ""
    if ($sector.Names -and $sector.Names.Count -gt 0) {
        # Names is an array of objects with a Text property
        $name = $sector.Names[0].Text
    } elseif ($sector.Name) {
        $name = $sector.Name
    }
    if ($name -eq "") { continue }

    $sx = [int]$sector.X
    $sy = [int]$sector.Y

    # Compute 1-based slot number for the 7x5 grid.
    $col  = $sx - $X_MIN       # 0-based column (0 = leftmost)
    $row  = $sy - $Y_MIN       # 0-based row    (0 = top)
    $slot = $row * $GRID_W + $col + 1

    $nameSafe = $name.Replace('\', '\\').Replace('"', '\"')
    $jsonItems.Add("{`"name`":`"$nameSafe`",`"x`":$sx,`"y`":$sy,`"defaultSlot`":`"$slot`"}")

    Write-Host ("  Slot {0,2}  ({1,2},{2,2})  {3}" -f $slot, $sx, $sy, $name)
}

if ($jsonItems.Count -eq 0) {
    Write-Host "ERROR: No sectors matched the grid bounds. Check API response format."
    exit 1
}

$json    = "[" + [string]::Join(",", $jsonItems) + "]"
$content = "// Auto-generated by convert_imperium.ps1 - do not edit manually.`n"
$content += "// Source: travellermap.com/api/universe  Grid: X[$X_MIN,$X_MAX] Y[$Y_MIN,$Y_MAX]`n"
$content += "window.IMPERIUM_SECTORS = $json;"

[System.IO.File]::WriteAllText($outputFile, $content, [System.Text.Encoding]::UTF8)

Write-Host ""
Write-Host "Done! Wrote js/imperium_data.js ($($jsonItems.Count) sector(s))."
